export const WORDS = [
  "AGENT",
  "WORLD",
  "ABOUT",
  "HEART",
  "WATER",
  "SIXTY",
  "BOARD",
  "MONTH",
  "MUSIC",
  "PARTY",
  "PIANO",
  "MOUTH",
  "WOMAN",
  "SUGAR",
  "AMBER",
  "DREAM",
  "LAUGH",
  "TIGER",
  "EARTH",
  "MONEY",
  "WORDS",
  "SMILE",
  "LEMON",
  "SOUTH",
  "AFTER",
  "STONE",
  "THING",
  "LIGHT",
  "STORY",
  "POWER",
  "TODAY",
  "RANGE",
  "PEARL",
  "VENOM",
  "PROXY",
  "ROUND",
  "HOVER",
  "CANDY",
  "ABOVE",
  "PHONE",
  "OTHER",
  "SMART",
  "BLACK",
  "MAGIC",
  "FRUIT",
  "RADIO",
  "ROYAL",
  "HONEY",
  "FLAKE",
  "SOUND",
]

export const INITIALKEYBOARDROWS = [
  [
    { alphabet: "Q", style: "" },
    { alphabet: "W", style: "" },
    { alphabet: "E", style: "" },
    { alphabet: "R", style: "" },
    { alphabet: "T", style: "" },
    { alphabet: "Y", style: "" },
    { alphabet: "U", style: "" },
    { alphabet: "I", style: "" },
    { alphabet: "O", style: "" },
    { alphabet: "P", style: "" },
  ],
  [
    { alphabet: "A", style: "" },
    { alphabet: "S", style: "" },
    { alphabet: "D", style: "" },
    { alphabet: "F", style: "" },
    { alphabet: "G", style: "" },
    { alphabet: "H", style: "" },
    { alphabet: "J", style: "" },
    { alphabet: "K", style: "" },
    { alphabet: "L", style: "" },
  ],
  [
    { alphabet: "Z", style: "" },
    { alphabet: "X", style: "" },
    { alphabet: "C", style: "" },
    { alphabet: "V", style: "" },
    { alphabet: "B", style: "" },
    { alphabet: "N", style: "" },
    { alphabet: "M", style: "" },
  ],
]
